# Default configuration for BORS external connections

connection_manager:
  ros__parameters:
    rosbridge_port: 9090
    foxglove_port: 8765
    webserver_port: 8080
    check_interval_seconds: 5.5

web_server:
  ros__parameters:
    port: 8080
    # Directory will be provided via launch file by default
