name: Sync external_connections to ROS2-WEB-monitor

on:
  push:
    branches: [ main ]
    paths:
      - 'ros/src/external_connections/**'

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source (BORS1-ROS2)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Stage files to sync
        run: |
          set -euo pipefail
          SRC_DIR="ros/src/external_connections"
          if [ ! -d "$SRC_DIR" ]; then
            echo "Source directory $SRC_DIR not found"
            exit 1
          fi
          rm -rf /tmp/sync
          mkdir -p /tmp/sync
          # copy contents (including dotfiles)
          rsync -a "$SRC_DIR"/ /tmp/sync/

      - name: Clone destination repo (ROS2-WEB-monitor)
        env:
          TOKEN: ${{ secrets.DEST_REPO_TOKEN }}
        run: |
          set -euo pipefail
          git clone "https://x-access-token:${TOKEN}@github.com/laszipt/ROS2-WEB-monitor.git" /tmp/dest
          cd /tmp/dest
          # ensure branch exists; adjust if using another branch
          git checkout main || git checkout -b main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy and commit changes
        run: |
          set -euo pipefail
          DEST_ROOT="/tmp/dest"
          DEST_DIR="${DEST_ROOT}/external_connections"
          mkdir -p "$DEST_DIR"
          # mirror the source subset into destination folder
          rsync -a --delete /tmp/sync/ "$DEST_DIR/"

          cd "$DEST_ROOT"

          # Avoid auth conflicts caused by Actions extraheader when pushing to another repo
          git config --unset-all http.https://github.com/.extraheader || true

          if ! git diff --quiet; then
            git add -A
            git commit -m "Sync ros/src/external_connections from BORS1-ROS2"
            git push origin main
          else
            echo "No changes to commit"
          fi
